name: Python application 2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  0 1 * * * 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Checkin
      run: |
        python3 checkin.py
      env: 
        SERVE: ${{ secrets.SERVE2 }}
        SCKEY: ${{ secrets.SCKEY2 }}
        COOKIE: ${{ secrets.COOKIE2 }}
